---
# tasks file for ansible-git-role

- name: Ansible Git | Set working directory
  ansible.builtin.set_fact:
    working_dir: "{{ git_working_dir | default(ansible_env.HOME, true) }}"
    git_repo_name: "{{ git_repo_url | regex_findall('[^\/]*.git$') | replace('.git', '') }}"

- name: Ansible Git | Extract repo name
  ansible.builtin.set_fact:
    git_repo: "{{ git_repo_name | join(' ') }}"

- name: Ansible Git | Extract repo name
  ansible.builtin.set_fact:
    git_repo_path: "{{ working_dir }}/{{ git_repo }}"

- name: Ansible Git | Clone operation
  when: git_action == 'clone'
  ansible.builtin.include_tasks:
    file: git_clone.yml

- name: Ansible Git | Push operation
  when: git_action == 'push'
  ansible.builtin.include_tasks:
    file: git_push.yml
